package equiv

import (
	"fmt"
	"html"
	"regexp"
	"strings"
)

// The guide predates any machine-readable interface, so its output has to be
// read out of the HTML. The markup is generated by Banner and is stable, but it
// is not well-formed enough for a strict parser: cells go unclosed and
// attributes are unquoted. These patterns are deliberately permissive.
var (
	tablePattern   = regexp.MustCompile(`(?is)<table.*?</table>`)
	rowPattern     = regexp.MustCompile(`(?is)<tr.*?</tr>`)
	cellPattern    = regexp.MustCompile(`(?is)<t[dh].*?</t[dh]>`)
	tagPattern     = regexp.MustCompile(`(?is)<[^>]*>`)
	spacePattern   = regexp.MustCompile(`\s+`)
	subjectPattern = regexp.MustCompile(`(?is)<select[^>]*name="purdue_subject_in"[^>]*>(.*?)</select>`)
	optionPattern  = regexp.MustCompile(`(?is)<option[^>]*value="([^"]*)"[^>]*>(.*?)</option>`)
)

// reportColumns is the column count of the equivalency table: the five transfer
// fields followed by four Purdue ones.
const reportColumns = 9

// parseSubjectOptions extracts the Purdue subject list from the search form.
func parseSubjectOptions(page string) ([]Option, error) {
	match := subjectPattern.FindStringSubmatch(page)
	if match == nil {
		return nil, fmt.Errorf("subject list not found on search form (page layout may have changed)")
	}

	var opts []Option
	seen := make(map[string]bool)
	for _, opt := range optionPattern.FindAllStringSubmatch(match[1], -1) {
		value := strings.TrimSpace(opt[1])
		if value == "" || seen[value] {
			continue
		}
		seen[value] = true
		opts = append(opts, Option{Text: textOf(opt[2]), Value: value})
	}
	return opts, nil
}

// parseReport extracts equivalencies from a results page. Any table without the
// expected header is layout or navigation chrome and is skipped.
func parseReport(page string) []Equivalency {
	var out []Equivalency

	for _, table := range tablePattern.FindAllString(page, -1) {
		rows := rowPattern.FindAllString(table, -1)
		if len(rows) < 2 || !isReportHeader(cellsOf(rows[0])) {
			continue
		}

		for _, row := range rows[1:] {
			cells := cellsOf(row)
			if len(cells) < reportColumns-1 {
				continue
			}
			e := Equivalency{
				TransferSchool:  cells[0],
				TransferSubject: cells[1],
				TransferCourse:  cells[2],
				TransferTitle:   cells[3],
				TransferCredits: cells[4],
				PurdueSubject:   cells[5],
				PurdueCourse:    cells[6],
				PurdueTitle:     cells[7],
			}
			if len(cells) >= reportColumns {
				e.PurdueCredits = cells[8]
			}
			if e.TransferSchool == "" && e.PurdueCourse == "" {
				continue // spacer row
			}
			// A blank transfer side continues the row above: the same course
			// also yields this second Purdue equivalency. Restate the transfer
			// side so each record stands alone.
			if e.TransferSchool == "" && len(out) > 0 {
				prev := out[len(out)-1]
				e.TransferSchool = prev.TransferSchool
				e.TransferSubject = prev.TransferSubject
				e.TransferCourse = prev.TransferCourse
				e.TransferTitle = prev.TransferTitle
				e.TransferCredits = prev.TransferCredits
				e.Continuation = true
			}
			out = append(out, e)
		}
	}
	return out
}

func isReportHeader(cells []string) bool {
	if len(cells) < reportColumns-1 {
		return false
	}
	return strings.Contains(strings.ToLower(strings.Join(cells, "|")), "purdue course")
}

func cellsOf(row string) []string {
	matches := cellPattern.FindAllString(row, -1)
	cells := make([]string, 0, len(matches))
	for _, cell := range matches {
		cells = append(cells, textOf(cell))
	}
	return cells
}

// textOf reduces a fragment of markup to its collapsed text content.
func textOf(fragment string) string {
	text := tagPattern.ReplaceAllString(fragment, " ")
	text = html.UnescapeString(text)
	return strings.TrimSpace(spacePattern.ReplaceAllString(text, " "))
}
